# This file was generated by the {rix} R package v0.9.0 on 2024-08-22
# with following call:
# >rix(r_ver = "4de4818c1ffa76d57787af936e8a23648bda6be4",
#  > r_pkgs = c("shiny",
#  > "fs",
#  > "languageserver",
#  > "pins",
#  > "archive",
#  > "s3fs",
#  > "DT",
#  > "DBI",
#  > "RSQLite",
#  > "lubridate",
#  > "pool",
#  > "dplyr",
#  > "dbplyr",
#  > "devtools",
#  > "testthat",
#  > "arrow",
#  > "Microsoft365R",
#  > "paws_storage",
#  > "sodium",
#  > "zip",
#  > "AzureStor",
#  > "shinytest2",
#  > "chromote"),
#  > system_pkgs = NULL,
#  > git_pkgs = NULL,
#  > ide = "radian",
#  > project_path = ".",
#  > overwrite = TRUE)
# It uses nixpkgs' revision 4de4818c1ffa76d57787af936e8a23648bda6be4 for reproducibility purposes
# which will install R version latest.
# Report any issues to https://github.com/b-rodrigues/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/4de4818c1ffa76d57787af936e8a23648bda6be4.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      shiny
      fs
      languageserver
      pins
      archive
      s3fs
      DT
      DBI
      RSQLite
      lubridate
      pool
      dplyr
      dbplyr
      devtools
      testthat
      arrow
      Microsoft365R
      paws_storage
      sodium
      zip
      AzureStor
      shinytest2
      shinyvalidate
      chromote;
  };
    
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      R
      glibcLocales
      nix;
  };
 
  wrapped_pkgs = pkgs.radianWrapper.override {
    packages = [  rpkgs  ];
  };
 
in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then  "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [  rpkgs  system_packages  wrapped_pkgs ];
  
}
